using System.Text.Json.Serialization;
using ChatApp.Realtime.Abstractions.Conversations;
using ChatApp.Realtime.Abstractions.Events;
using ChatApp.Realtime.Abstractions.Messaging;
using ChatApp.Realtime.Abstractions.Attachments;
using ChatApp.Realtime.Abstractions.Messaging.History;
using ChatApp.Realtime.Abstractions.Relationships;
using ChatApp.Realtime.Abstractions.Stores;
using ChatApp.Realtime.Abstractions.Sync;

namespace ChatApp.Realtime.Infrastructure.Core.Serialization;

[JsonSerializable(typeof(RealtimeEvent))]
[JsonSerializable(typeof(IncomingMessageCommand))]
[JsonSerializable(typeof(MessageProcessResult))]
[JsonSerializable(typeof(DeadLetterMessage))]
[JsonSerializable(typeof(RealtimeChatMessagePayload))]
[JsonSerializable(typeof(AttachmentRef))]
[JsonSerializable(typeof(List<AttachmentRef>))]
[JsonSerializable(typeof(RealtimeConversationChangedPayload))]
[JsonSerializable(typeof(RealtimeConversationDissolvedPayload))]
[JsonSerializable(typeof(RealtimeUnreadCountChangedPayload))]
[JsonSerializable(typeof(RealtimeConversationReadPayload))]
[JsonSerializable(typeof(AttachmentBlobsPurgePayload))]
[JsonSerializable(typeof(ConversationListQuery))]
[JsonSerializable(typeof(ConversationListPage))]
[JsonSerializable(typeof(ConversationListCursor))]
[JsonSerializable(typeof(ConversationListItem))]
[JsonSerializable(typeof(List<ConversationListItem>))]
[JsonSerializable(typeof(ConversationMarkReadCommand))]
[JsonSerializable(typeof(ConversationMarkReadResult))]
[JsonSerializable(typeof(ConversationSetPrefsCommand))]
[JsonSerializable(typeof(ConversationSetPrefsResult))]
[JsonSerializable(typeof(GroupConversationCommand))]
[JsonSerializable(typeof(GroupConversationResult))]
[JsonSerializable(typeof(MessageReader))]
[JsonSerializable(typeof(List<MessageReader>))]
[JsonSerializable(typeof(ConversationMemberItem))]
[JsonSerializable(typeof(List<ConversationMemberItem>))]
[JsonSerializable(typeof(RealtimeMemberJoinedPayload))]
[JsonSerializable(typeof(RealtimeMembersAddedPayload))]
[JsonSerializable(typeof(RealtimeMemberLeftPayload))]
[JsonSerializable(typeof(RealtimeMemberRemovedPayload))]
[JsonSerializable(typeof(RealtimeRoleChangedPayload))]
[JsonSerializable(typeof(MessageRecallCommand))]
[JsonSerializable(typeof(MessageRecallResult))]
[JsonSerializable(typeof(RealtimeMessageRecalledPayload))]
[JsonSerializable(typeof(MessageEditCommand))]
[JsonSerializable(typeof(MessageEditResult))]
[JsonSerializable(typeof(RealtimeMessageEditedPayload))]
[JsonSerializable(typeof(MessageReactionCommand))]
[JsonSerializable(typeof(MessageReactionResult))]
[JsonSerializable(typeof(RealtimeReactionAddedPayload))]
[JsonSerializable(typeof(RealtimeReactionRemovedPayload))]
[JsonSerializable(typeof(MessageReactionSummary))]
[JsonSerializable(typeof(List<MessageReactionSummary>))]
[JsonSerializable(typeof(MessageReceiptCommand))]
[JsonSerializable(typeof(RealtimeMessageReceiptPayload))]
[JsonSerializable(typeof(RealtimeDomainNotificationPayload))]
[JsonSerializable(typeof(MessageHistoryQuery))]
[JsonSerializable(typeof(MessageHistoryPage))]
[JsonSerializable(typeof(MessageHistoryCursor))]
[JsonSerializable(typeof(RealtimeHistoryMessage))]
[JsonSerializable(typeof(List<RealtimeHistoryMessage>))]
[JsonSerializable(typeof(SyncBootstrapQuery))]
[JsonSerializable(typeof(SyncBootstrapPage))]
[JsonSerializable(typeof(ConversationSyncWatermark))]
[JsonSerializable(typeof(List<ConversationSyncWatermark>))]
[JsonSerializable(typeof(ConversationHistoryCatchUp))]
[JsonSerializable(typeof(List<ConversationHistoryCatchUp>))]
[JsonSerializable(typeof(SyncCursorResetRequired))]
[JsonSerializable(typeof(List<SyncCursorResetRequired>))]
[JsonSerializable(typeof(SyncCursorResetReason))]
[JsonSerializable(typeof(AttachmentFinalizeCommand))]
[JsonSerializable(typeof(AttachmentFinalizeResult))]
[JsonSerializable(typeof(RelationshipCommand))]
[JsonSerializable(typeof(RelationshipCommandResult))]
[JsonSerializable(typeof(RelationshipListQuery))]
[JsonSerializable(typeof(RelationshipListResult))]
[JsonSerializable(typeof(RelationshipListItem))]
[JsonSerializable(typeof(List<RelationshipListItem>))]
[JsonSerializable(typeof(RelationshipListType))]
[JsonSerializable(typeof(RelationshipSyncWatermark))]
[JsonSerializable(typeof(List<RelationshipSyncWatermark>))]
[JsonSerializable(typeof(RelationshipCatchUp))]
[JsonSerializable(typeof(List<RelationshipCatchUp>))]
[JsonSerializable(typeof(RelationshipSyncCursor))]
[JsonSerializable(typeof(List<RelationshipSyncCursor>))]
public sealed partial class RealtimeJsonSerializerContext : JsonSerializerContext
{
}