using System.Text.Json.Serialization;
using ChatApp.Realtime.Abstractions.Conversations;
using ChatApp.Realtime.Abstractions.Events;
using ChatApp.Realtime.Abstractions.Messaging;
using ChatApp.Realtime.Abstractions.Messaging.History;
using ChatApp.Realtime.Abstractions.Sync;
using ChatApp.Realtime.Integration.Ephemeral;

namespace ChatApp.Realtime.Integration.Serialization;

[JsonSourceGenerationOptions(PropertyNameCaseInsensitive = true)]
[JsonSerializable(typeof(IncomingMessageCommand))]
[JsonSerializable(typeof(MessageReceiptCommand))]
[JsonSerializable(typeof(RealtimeEvent))]
[JsonSerializable(typeof(DeadLetterMessage))]
[JsonSerializable(typeof(RealtimeChatMessagePayload))]
[JsonSerializable(typeof(AttachmentRef))]
[JsonSerializable(typeof(List<AttachmentRef>))]
[JsonSerializable(typeof(RealtimeConversationChangedPayload))]
[JsonSerializable(typeof(RealtimeMessageReceiptPayload))]
[JsonSerializable(typeof(RealtimeDomainNotificationPayload))]
[JsonSerializable(typeof(MessageHistoryQuery))]
[JsonSerializable(typeof(MessageHistoryPage))]
[JsonSerializable(typeof(MessageHistoryCursor))]
[JsonSerializable(typeof(RealtimeHistoryMessage))]
[JsonSerializable(typeof(List<RealtimeHistoryMessage>))]
[JsonSerializable(typeof(ConversationListQuery))]
[JsonSerializable(typeof(ConversationListPage))]
[JsonSerializable(typeof(ConversationListItem))]
[JsonSerializable(typeof(ConversationListCursor))]
[JsonSerializable(typeof(List<ConversationListItem>))]
[JsonSerializable(typeof(ConversationMarkReadCommand))]
[JsonSerializable(typeof(ConversationMarkReadResult))]
[JsonSerializable(typeof(ConversationSetPrefsCommand))]
[JsonSerializable(typeof(ConversationSetPrefsResult))]
[JsonSerializable(typeof(GroupConversationCommand))]
[JsonSerializable(typeof(GroupConversationResult))]
[JsonSerializable(typeof(ConversationMemberItem))]
[JsonSerializable(typeof(List<ConversationMemberItem>))]
[JsonSerializable(typeof(RealtimeMemberJoinedPayload))]
[JsonSerializable(typeof(RealtimeMemberLeftPayload))]
[JsonSerializable(typeof(RealtimeMemberRemovedPayload))]
[JsonSerializable(typeof(RealtimeRoleChangedPayload))]
[JsonSerializable(typeof(MessageRecallCommand))]
[JsonSerializable(typeof(MessageRecallResult))]
[JsonSerializable(typeof(RealtimeMessageRecalledPayload))]
[JsonSerializable(typeof(MessageEditCommand))]
[JsonSerializable(typeof(MessageEditResult))]
[JsonSerializable(typeof(RealtimeMessageEditedPayload))]
[JsonSerializable(typeof(MessageReactionCommand))]
[JsonSerializable(typeof(MessageReactionResult))]
[JsonSerializable(typeof(RealtimeReactionAddedPayload))]
[JsonSerializable(typeof(RealtimeReactionRemovedPayload))]
[JsonSerializable(typeof(MessageReactionSummary))]
[JsonSerializable(typeof(List<MessageReactionSummary>))]
[JsonSerializable(typeof(SyncBootstrapQuery))]
[JsonSerializable(typeof(SyncBootstrapPage))]
[JsonSerializable(typeof(ConversationSyncWatermark))]
[JsonSerializable(typeof(List<ConversationSyncWatermark>))]
[JsonSerializable(typeof(ConversationHistoryCatchUp))]
[JsonSerializable(typeof(List<ConversationHistoryCatchUp>))]
[JsonSerializable(typeof(SyncCursorResetRequired))]
[JsonSerializable(typeof(List<SyncCursorResetRequired>))]
[JsonSerializable(typeof(SyncCursorResetReason))]
[JsonSerializable(typeof(RealtimeUnreadCountChangedPayload))]
[JsonSerializable(typeof(AttachmentBlobsPurgePayload))]
[JsonSerializable(typeof(EphemeralTypingEvent))]
[JsonSerializable(typeof(EphemeralPresenceEvent))]
[JsonSerializable(typeof(PresenceAuthorizeQuery))]
[JsonSerializable(typeof(PresenceAuthorizeResponse))]
[JsonSerializable(typeof(List<long>))]
internal sealed partial class RealtimeIntegrationJsonContext : JsonSerializerContext
{
}
